fix/audio playback cut off
eve-autonomy/ad_sound_manager pull request #7
Opened 2022-07-28 08:26 UTC by a-higuchi

# Description
## Current problem
There was a problem that the beginning of the audio was not played in the STATE_WAITING_CALL_PERMISSION state.  
On some devices, after stopping audio playback for a period of time, the audio device automatically goes idle and does not play the beginning of the audio when it returns from idle.  

## Countermeasures
Change the stopped portion of the BGM to silent playback. 
This change prevents audio devices from becoming idle while the system is running. 

## Review Procedure
By implementing the countermeasures, it was confirmed that the problem that the beginning of the audio is not played in the STATE_WAITING_CALL_PERMISSION state does not occur.  

 * Make sure the description is valid.
 * Make sure that what is described in the description matches the implementation.

2022-08-02 07:21 UTC, yn-mrse commented
@a-higuchi 
Thank you for your contribution!
Please describe the test method that was specifically carried out.

2022-08-02 07:57 UTC, yn-mrse approved these changes

2022-08-02 08:24 UTC, yn-mrse requested changes
@a-higuchi 
Could you please add the purpose and function of this silent audio playback to the README?
If this is not documented, the design becomes difficult to maintain.

2022-08-03 04:58 UTC, a-higuchi commented
> @a-higuchi Could you please add the purpose and function of this silent audio playback to the README? If this is not documented, the design becomes difficult to maintain.

2022-08-03 05:00 UTC, a-higuchi commented
> > @a-higuchi Could you please add the purpose and function of this silent audio playback to the README? If this is not documented, the design becomes difficult to maintain.

Added silent playback of BGM to Readme.

> @a-higuchi Thank you for your contribution! Please describe the test method that was specifically carried out.

Added specific test method.

2022-08-08 04:45 UTC, yn-mrse approved these changes

2022-08-08 04:56 UTC, merged